version: '3.8'

services:
  backend:
    build: .
    image: discord-backend:latest
    container_name: discord-backend-container
    restart: always
    ports:
      - "80:5000"
    env_file:
      - .env
